### ISSUE TITLE
Can't exit mail menu

### ISSUE THREAD

**Issue by tmtowtdi** [Jazzeroki/JavaClientLE#1]
When the Messages menu displays tags:

Mail Box: You have 471 new messages
Enter a number for your selection
1, Correspondence
2, Intelligence
3, Spies
4, Trade
5, Complaint
6, Excavator
7, Parliament
8, Alert
9, Attack
0, Return to Main Menu
Enter a selection

...I enter "0" and it shows me Attack messages - seems I can't return to the main menu and have to sigint to get out.

Entering "9" returns "Invalid Selection" and simply re-displays the same tag menu.  Entering "8" does show Alert messages.

**Comment by Jazzeroki** [comment]
I’ll have to look into this one.  You found one of those menu infinite loops that I’ve been hunting down.  I think I already know where to go to fix this one.  I’m thinking it may be a case that I missed in the switch statement.

From: Jonathan Barton
Sent: ‎Thursday‎, ‎June‎ ‎5‎, ‎2014 ‎12‎:‎16‎ ‎AM
To: Jazzeroki/JavaClientLE

When the Messages menu displays tags:

Mail Box: You have 471 new messages
Enter a number for your selection
1, Correspondence
2, Intelligence
3, Spies
4, Trade
5, Complaint
6, Excavator
7, Parliament
8, Alert
9, Attack
0, Return to Main Menu
Enter a selection

...I enter "0" and it shows me Attack messages - seems I can't return to the main menu and have to sigint to get out.

Entering "9" returns "Invalid Selection" and simply re-displays the same tag menu. Entering "8" does show Alert messages.

**Comment by tmtowtdi** [comment]
Closing because TLE is dead.
