### ISSUE TITLE
Captcha Test

### ISSUE THREAD

**Issue by tmtowtdi** [Jazzeroki/JavaClientLE#2]
I'm on Ubuntu so I might be getting different output for this than you are if you're on Windows.

The captcha test did work in that it showed the captcha image in my browser in a new tab, and it accepted my answer.  But I got some output that looks like something's unhappy:

```
1: Captcha test
0: to return to main menu
1
https://us1.lacunaexpanse.com/captcha
{"jsonrpc":"2.0","id":1,"result":{"url":"https://us1.lacunaexpanse.com//captcha/a7/a7c81477-3e58-4325-8c94-7e3da33ed55c.png","guid":"a7c81477-3e58-4325-8c94-7e3da33ed55c"}}
Please wait a moment while the captcha is loaded in a browser window
After the captcha has appeared enter the answer and push enter

(process:19035): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
36
https://us1.lacunaexpanse.com/captcha
note what the reply here looks like to see the indicator that the captcha worked so the if statment can be written
{"jsonrpc":"2.0","id":1,"result":1}
```

**Comment by Jazzeroki** [comment]
Did you find this in the experimental menu?

I don’t know that I’ve seen this before: (process:19035): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

Anyways I’ve included captchas now on methods that require them.  I still need to do something about what happens say if you enter the captcha answer incorrectly.  Also I know it’s not handling once it or the session times out.  Those are still on my todo list.

Sent from Windows Mail

From: Jonathan Barton
Sent: ‎Thursday‎, ‎June‎ ‎5‎, ‎2014 ‎12‎:‎31‎ ‎AM
To: Jazzeroki/JavaClientLE

I'm on Ubuntu so I might be getting different output for this than you are if you're on Windows.

The captcha test did work in that it showed the captcha image in my browser in a new tab, and it accepted my answer. But I got some output that looks like something's unhappy:
1: Captcha test
0: to return to main menu
1
https://us1.lacunaexpanse.com/captcha
{"jsonrpc":"2.0","id":1,"result":{"url":"https://us1.lacunaexpanse.com//captcha/a7/a7c81477-3e58-4325-8c94-7e3da33ed55c.png","guid":"a7c81477-3e58-4325-8c94-7e3da33ed55c"}}
Please wait a moment while the captcha is loaded in a browser window
After the captcha has appeared enter the answer and push enter

(process:19035): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
36
https://us1.lacunaexpanse.com/captcha
note what the reply here looks like to see the indicator that the captcha worked so the if statment can be written
{"jsonrpc":"2.0","id":1,"result":1}

**Comment by tmtowtdi** [comment]
Closing because TLE is dead.
