### ISSUE TITLE
Shipbuilder

### ISSUE THREAD

**Issue by tmtowtdi** [Jazzeroki/JavaClientLE#3]
I tried buliding ships on a planet with 4 level 30 shipyards but only 74 available spaceport slots.  The build ship thing tried to fill all 4 shipyards with excavator builds, here's the output:

```
Fill shipyards with:
1: Snark3
2: Sweeper
3: Fighter
4: Scow
5: Scow Fast
6: Scow Large
7: Scow Mega, Warning these take a long time to build
8: Fissure Sealer
11: Hulk Huge
12: detonator
13: Smuggler Ship
14: Placebo 6
15: Bleeder
16: Thud
17: Sec. Min. Seeker
18: Supply Pod 4
19: Scanner
0: Return to previous menu
9
shipyard
https://us1.lacunaexpanse.com/shipyard
shipyard
https://us1.lacunaexpanse.com/shipyard
shipyard
https://us1.lacunaexpanse.com/shipyard
Server Error IO Exception possible bad url
shipyard
https://us1.lacunaexpanse.com/shipyard
Server Error IO Exception possible bad url
120 excavator now under construction on bmots07
```

It ended up adding 30 ships to each of two shipyards (leaving me with only 14 slots left).  So the next two attempts to add 30 more ships to the other two shipyards failed (as expected).

So the client basically did the right thing, it just didn't handle the server exceptions.

**Comment by Jazzeroki** [comment]
Yes this one is working as intended.  It just fills shipyards with ships based on their level.  It works best with all shipyards at level 30.  It doesn’t bother checking how many ports are available.  If it gets a server error, it just spits out the error message you saw below, ignores it and moves on with the script.  So yes wasted rpcs, but considering the low number used by this request I didn’t consider it to be that big of a deal.

Sent from Windows Mail

From: Jonathan Barton
Sent: ‎Thursday‎, ‎June‎ ‎5‎, ‎2014 ‎1‎:‎20‎ ‎AM
To: Jazzeroki/JavaClientLE

I tried buliding ships on a planet with 4 level 30 shipyards but only 74 available spaceport slots. The build ship thing tried to fill all 4 shipyards with excavator builds, here's the output:
Fill shipyards with:
1: Snark3
2: Sweeper
3: Fighter
4: Scow
5: Scow Fast
6: Scow Large
7: Scow Mega, Warning these take a long time to build
8: Fissure Sealer
11: Hulk Huge
12: detonator
13: Smuggler Ship
14: Placebo 6
15: Bleeder
16: Thud
17: Sec. Min. Seeker
18: Supply Pod 4
19: Scanner
0: Return to previous menu
9
shipyard
https://us1.lacunaexpanse.com/shipyard
shipyard
https://us1.lacunaexpanse.com/shipyard
shipyard
https://us1.lacunaexpanse.com/shipyard
Server Error IO Exception possible bad url
shipyard
https://us1.lacunaexpanse.com/shipyard
Server Error IO Exception possible bad url
120 excavator now under construction on bmots07

It ended up adding 30 ships to each of two shipyards (leaving me with only 14 slots left). So the next two attempts to add 30 more ships to the other two shipyards failed (as expected).

So the client basically did the right thing, it just didn't handle the server exceptions.

**Comment by tmtowtdi** [comment]
Closing because TLE is dead.
